// Date: 7/23/2013 2:45:02 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelSupaCreep extends ModelBase
{
  //fields
    ModelRenderer leg1;
    ModelRenderer leg2;
    ModelRenderer body;
    ModelRenderer arm1;
    ModelRenderer arm2;
    ModelRenderer head;
  
  public ModelSupaCreep()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      leg1 = new ModelRenderer(this, 28, 25);
      leg1.addBox(-3F, 0F, -3F, 2, 5, 2);
      leg1.setRotationPoint(0F, 19F, 2F);
      leg1.setTextureSize(64, 32);
      leg1.mirror = true;
      setRotation(leg1, 0F, 0F, 0F);
      leg2 = new ModelRenderer(this, 40, 25);
      leg2.addBox(-1F, 0F, -1F, 2, 5, 2);
      leg2.setRotationPoint(2F, 19F, 0F);
      leg2.setTextureSize(64, 32);
      leg2.mirror = true;
      setRotation(leg2, 0F, 0F, 0F);
      body = new ModelRenderer(this, 28, 10);
      body.addBox(0F, 0F, 0F, 4, 6, 6);
      body.setRotationPoint(3F, 13F, -2F);
      body.setTextureSize(64, 32);
      body.mirror = true;
      setRotation(body, 0F, -1.570796F, 0F);
      arm1 = new ModelRenderer(this, 50, 11);
      arm1.addBox(-1F, 0F, -1F, 2, 8, 2);
      arm1.setRotationPoint(3F, 14F, 0F);
      arm1.setTextureSize(64, 32);
      arm1.mirror = true;
      setRotation(arm1, -0.418879F, -1.570796F, 0F);
      arm2.mirror = true;
      arm2 = new ModelRenderer(this, 18, 10);
      arm2.addBox(-1F, 0F, -1F, 2, 8, 2);
      arm2.setRotationPoint(-3F, 14F, 0F);
      arm2.setTextureSize(64, 32);
      arm2.mirror = true;
      setRotation(arm2, 0.418879F, -1.570796F, 0.1919862F);
      arm2.mirror = false;
      head = new ModelRenderer(this, 30, 0);
      head.addBox(-2F, -4F, -2F, 4, 4, 4);
      head.setRotationPoint(0F, 13F, 0F);
      head.setTextureSize(64, 32);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    leg1.render(f5);
    leg2.render(f5);
    body.render(f5);
    arm1.render(f5);
    arm2.render(f5);
    head.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
