// Date: 7/24/2013 9:45:28 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelNew extends ModelBase
{
  //fields
    ModelRenderer Head;
    ModelRenderer Body;
    ModelRenderer RightArm1;
    ModelRenderer LeftArm1;
    ModelRenderer RightLeg1;
    ModelRenderer LeftLeg1;
    ModelRenderer LeftArm2;
    ModelRenderer LeftArm3;
    ModelRenderer RightArm2;
    ModelRenderer RightArm3;
    ModelRenderer LeftLeg2;
    ModelRenderer RightLeg2;
    ModelRenderer Body2;
    ModelRenderer Body3;
    ModelRenderer Body4;
    ModelRenderer Body5;
    ModelRenderer Ear1;
    ModelRenderer Ear2;
  
  public ModelNew()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      Head = new ModelRenderer(this, 47, 46);
      Head.addBox(-4F, -8F, -4F, 8, 8, 8);
      Head.setRotationPoint(0F, -14F, 0F);
      Head.setTextureSize(128, 128);
      Head.mirror = true;
      setRotation(Head, 0F, 0F, 0F);
      Body = new ModelRenderer(this, 43, 66);
      Body.addBox(-4F, 0F, -2F, 8, 12, 12);
      Body.setRotationPoint(0F, -14F, 0F);
      Body.setTextureSize(128, 128);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      RightArm1 = new ModelRenderer(this, 52, 0);
      RightArm1.addBox(-1F, 0F, -1F, 2, 30, 2);
      RightArm1.setRotationPoint(-3F, -10F, 0F);
      RightArm1.setTextureSize(128, 128);
      RightArm1.mirror = true;
      setRotation(RightArm1, -0.122173F, -0.0698132F, 0.2617994F);
      LeftArm1.mirror = true;
      LeftArm1 = new ModelRenderer(this, 85, 88);
      LeftArm1.addBox(-1F, 0F, -1F, 2, 30, 2);
      LeftArm1.setRotationPoint(3F, -9F, 0F);
      LeftArm1.setTextureSize(128, 128);
      LeftArm1.mirror = true;
      setRotation(LeftArm1, -0.122173F, -0.0698132F, -0.2617994F);
      LeftArm1.mirror = false;
      RightLeg1 = new ModelRenderer(this, 45, 93);
      RightLeg1.addBox(-1F, 0F, -1F, 2, 30, 2);
      RightLeg1.setRotationPoint(-2F, -2F, 0F);
      RightLeg1.setTextureSize(128, 128);
      RightLeg1.mirror = true;
      setRotation(RightLeg1, 0F, 0F, 0F);
      LeftLeg1.mirror = true;
      LeftLeg1 = new ModelRenderer(this, 73, 93);
      LeftLeg1.addBox(-1F, 0F, -1F, 2, 30, 2);
      LeftLeg1.setRotationPoint(2F, -2F, 0F);
      LeftLeg1.setTextureSize(128, 128);
      LeftLeg1.mirror = true;
      setRotation(LeftLeg1, 0F, 0F, 0F);
      LeftLeg1.mirror = false;
      LeftArm2 = new ModelRenderer(this, 68, 0);
      LeftArm2.addBox(-1F, 0F, -1F, 2, 30, 2);
      LeftArm2.setRotationPoint(4F, -8F, 6F);
      LeftArm2.setTextureSize(128, 128);
      LeftArm2.mirror = true;
      setRotation(LeftArm2, 0.0698132F, -0.0872665F, -0.6108652F);
      LeftArm3 = new ModelRenderer(this, 98, 81);
      LeftArm3.addBox(-1F, 0F, -1F, 2, 30, 2);
      LeftArm3.setRotationPoint(3F, -5F, 13F);
      LeftArm3.setTextureSize(128, 128);
      LeftArm3.mirror = true;
      setRotation(LeftArm3, 0.1047198F, -0.2094395F, -0.8726646F);
      RightArm2 = new ModelRenderer(this, 32, 89);
      RightArm2.addBox(-1F, 0F, -1F, 2, 30, 2);
      RightArm2.setRotationPoint(-4F, -8F, 7F);
      RightArm2.setTextureSize(128, 128);
      RightArm2.mirror = true;
      setRotation(RightArm2, -0.0698132F, -0.0872665F, 0.6108652F);
      RightArm3 = new ModelRenderer(this, 20, 80);
      RightArm3.addBox(-1F, 0F, -1F, 2, 30, 2);
      RightArm3.setRotationPoint(-3F, -5F, 17F);
      RightArm3.setTextureSize(128, 128);
      RightArm3.mirror = true;
      setRotation(RightArm3, -0.1047198F, 0.2094395F, 0.8726646F);
      LeftLeg2 = new ModelRenderer(this, 35, 26);
      LeftLeg2.addBox(-1F, 0F, -1F, 2, 26, 2);
      LeftLeg2.setRotationPoint(2F, -2F, 17F);
      LeftLeg2.setTextureSize(128, 128);
      LeftLeg2.mirror = true;
      setRotation(LeftLeg2, 0F, 0F, 0F);
      RightLeg2 = new ModelRenderer(this, 88, 50);
      RightLeg2.addBox(-1F, 0F, -1F, 2, 26, 2);
      RightLeg2.setRotationPoint(-2F, -2F, 17F);
      RightLeg2.setTextureSize(128, 128);
      RightLeg2.mirror = true;
      setRotation(RightLeg2, 0F, 0F, 0F);
      Body2 = new ModelRenderer(this, 3, 60);
      Body2.addBox(0F, 0F, 0F, 8, 8, 10);
      Body2.setRotationPoint(-4F, -10F, 10F);
      Body2.setTextureSize(128, 128);
      Body2.mirror = true;
      setRotation(Body2, 0F, 0F, 0F);
      Body3 = new ModelRenderer(this, 11, 47);
      Body3.addBox(-1F, -2F, 0F, 4, 4, 6);
      Body3.setRotationPoint(-1F, -5F, 20F);
      Body3.setTextureSize(128, 128);
      Body3.mirror = true;
      setRotation(Body3, 0F, 0F, 0F);
      Body4 = new ModelRenderer(this, 10, 33);
      Body4.addBox(-2F, -2F, 0F, 3, 3, 8);
      Body4.setRotationPoint(0.5F, -4F, 26F);
      Body4.setTextureSize(128, 128);
      Body4.mirror = true;
      setRotation(Body4, 0.2617994F, 0F, 0F);
      Body5 = new ModelRenderer(this, 12, 17);
      Body5.addBox(-1F, -1F, 0F, 2, 2, 8);
      Body5.setRotationPoint(0F, -7F, 33F);
      Body5.setTextureSize(128, 128);
      Body5.mirror = true;
      setRotation(Body5, 0.6981317F, 0F, 0F);
      Ear1 = new ModelRenderer(this, 50, 37);
      Ear1.addBox(-1F, -4F, -1F, 2, 4, 2);
      Ear1.setRotationPoint(-3F, -21F, -3F);
      Ear1.setTextureSize(128, 128);
      Ear1.mirror = true;
      setRotation(Ear1, 0.6108652F, 0.5235988F, -0.3490659F);
      Ear2 = new ModelRenderer(this, 68, 37);
      Ear2.addBox(-1F, -4F, -1F, 2, 4, 2);
      Ear2.setRotationPoint(3F, -21F, -3F);
      Ear2.setTextureSize(128, 128);
      Ear2.mirror = true;
      setRotation(Ear2, 0.6108652F, -0.5235988F, 0.3490659F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Head.render(f5);
    Body.render(f5);
    RightArm1.render(f5);
    LeftArm1.render(f5);
    RightLeg1.render(f5);
    LeftLeg1.render(f5);
    LeftArm2.render(f5);
    LeftArm3.render(f5);
    RightArm2.render(f5);
    RightArm3.render(f5);
    LeftLeg2.render(f5);
    RightLeg2.render(f5);
    Body2.render(f5);
    Body3.render(f5);
    Body4.render(f5);
    Body5.render(f5);
    Ear1.render(f5);
    Ear2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
